### ISSUE TITLE
Home Page Links

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#100]
At the top of the homepage currently the links are: How It Works - Pricing - Contact - Portal

I would like the links to be: 

How It Works
when clicked this link would simply scroll down the homepage to the area below the picture at the top of the homepage, in the future this area below the graphic with the free trial form will contain content that describes how RevuCue works

Pricing
when clicked this would scroll down on the homepage again to be right below the "How It Works" content, and this would be a pricing table with "sign up now" buttons below the three types of monthly plans 

Learn
when clicked this would redirect the viewer to the "blog" page revucue.com/learn which you created before

Portal
this would retain its functionality as it works now

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Nice
