### ISSUE TITLE
Email Title

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#102]
when a user creates an email template in the "Email Templates" page there is a form field that says "Email Title" and I have noticed that people are confused as to whether or not this is the subject of the email (which it is not) or if it is the label that only they will see, so I want to clarify this, I would like the title of this form field to be changed to:

"Email Title (This title will be seen in the body of your outgoing emails above your logo.)"

This change will also have to be made on the email pop-up within the existing customer table.

Also the table column labels on the "EMAIL TEMPLATES" page the heading that now says "EMAIL NAME" on the three tables should say "EMAIL TITLE"

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Nice
