### ISSUE TITLE
R & R Settings

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#103]
within each page under the R&R Settings tab (FORM ELEMENTS - RATE WEBPAGE - REVIEW LINKS - EMAIL TEMPLATES) there are tables on each of these pages, and each table has a title, for example on the FORM ELEMENTS page the title of the table is:

"FORM ELEMENTS: Customize your "Add New Customer Form" by turning ON or OFF each of the below form elements."

on all of these tables I would like the main title like "FORM ELEMENTS:" to stay as it is

but all of the descriptive text after that title, for example:
"Customize your "Add New Customer Form" by turning ON or OFF each of the below form elements."
to be a smaller font size, a font size closer to the font size that is used in the tables (looks like around 12pt??) this way it will look better and be easier to read

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
I wanted you to leave the title portion of the text big, so "FORM ELEMENTS:" would be big and bold as it was and all the other text following it would be small as you have made it now

**Comment by invokelocal** [comment]
So the text:

"FORM ELEMENTS:" would be lage text, and

"Customize your "Add New Customer Form" by turning ON or OFF each of the below form elements." would be small text as you have it now, 

this would apply to all headings

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Nice!
