### ISSUE TITLE
Add New Customer Form

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#104]
in the form fields of the add new customer form I would like you to code in "Contextual Keyboards" otherwise known as "Mobile Keyboard Input Types" this would make the keyboard on a smartphone or tablet only display the characters needed for the form field, so for the Phone Number input field the keyboard would only be numbers and for the Email form field the keyboard would display the "@" and so on...

And on the Phone Number form field I would like you to format that form field to be specific to phone numbers so the "     -     -        " would be present inside the form field and would only allow you to enter numbers like "302-234-3455"

And I would like the following form fields to have the indicated lengths, and where ever applicable change the "mobile input keyboard" to match the input type:

First Name: 20 Characters Long

Last Name: 20 Characters Long

Company Name: 30 Characters Long

Email: 30 Characters Long (email input formatting)

Phone Number: 10 Characters Long (with phone number formatting in the field, and numbers only)

Address Line 1: 25 Characters Long

Address Line 2: 25 Characters Long

City: 25 Characters Long 

State: keep it as is 
 
Zip Code: 5 Characters Long (numbers only)

Notes: keep it as is

Estimated Date: keep it as is

**Comment by invokelocal** [comment]
Also I do not want to limit the form field lengths to what I have above, only make them look that long, so even though the email form field will be set to 30 characters long, if the email is 42 characters long it will still allow the user to input this email, the reason for this change is just to make the form look better on computers and tablets hopefully

**Comment by invokelocal** [comment]
I hope this is not confusing you, the look of the form fields will be the lengths I indicated above, but if a user inputs data that is longer than the form field allow it, as you had previously...

**Comment by invokelocal** [comment]
Here is a link to a page that talks about the mobile input types, it may or may not be helpful:

http://uxmovement.com/mobile/input-types-give-users-the-right-keyboard-on-mobile-forms/

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
I don't think you got what I was trying to fix here, on mobile the contextual keyboard is working but attached is a screen shot from my computer
![badscreen](https://cloud.githubusercontent.com/assets/10223970/7041848/b7a187ea-dda2-11e4-9580-46f49bad8fad.png)

**Comment by invokelocal** [comment]
the purpose was to limit the length of the form fields and the form fileds are still waaaay too long as seen in the picture

**Comment by invokelocal** [comment]
![badscreen](https://cloud.githubusercontent.com/assets/10223970/7041896/06af1032-dda3-11e4-95f8-11ee768f06d2.png)

**Comment by invokelocal** [comment]
the form fields are way too lond, for instance the "Zip Code" is always 5 digits long, you have split up the phone number fields??

**Comment by invokelocal** [comment]
![checkout-form-field-descriptions-5-kohls](https://cloud.githubusercontent.com/assets/10223970/7041989/f4901198-dda3-11e4-8869-f3c96187847d.png)

**Comment by invokelocal** [comment]
that was a n example I found online of a telephone number form field, I think it is a setting in the DB??

**Comment by invokelocal** [comment]
(I know you are still coding) but on my screen my form now looks like the picture attached, if possible it would be best to standardize the length of some of the fields, put the "Last Name" below the "First Name" and center the entire form, so:

First Name: 30 Characters Long

Last Name: 30 Characters Long

Company Name: 30 Characters Long

Email: 30 Characters Long (email input formatting)

Phone Number: 10 Characters Long (with phone number formatting in the field, and numbers only)

Address Line 1: 30 Characters Long

Address Line 2: 30 Characters Long

City: 30 Characters Long

State: keep it as is

Zip Code: 5 Characters Long (numbers only)

Notes: If you can make the field as wide as the ones with 30 charachters but tall or deep as it is now...

Estimated Date: keep it as is

**Comment by invokelocal** [comment]
![form1](https://cloud.githubusercontent.com/assets/10223970/7042483/daae1a3c-dda7-11e4-94c9-0dae61e9096f.png)

**Comment by invokelocal** [comment]
If we could get it to look like this:
![group](https://cloud.githubusercontent.com/assets/10223970/7042683/34299a9a-dda9-11e4-9181-fb1a798cb7f5.png)

**Comment by orientationsys** [comment]
I have change the template . Can you give me the link about the contact phone number picture.

**Comment by invokelocal** [comment]
ok, my form still looks like the picture I attached, if possible I want it to look organized on the PC also, I think it is a form setting for the "(   )    -       ", I will find the code, one minute
![group](https://cloud.githubusercontent.com/assets/10223970/7042935/2928d47e-ddab-11e4-8c42-9f02c542bdc6.png)

**Comment by invokelocal** [comment]
this url might help, and I attached a screen shot:

http://stackoverflow.com/questions/21650617/html-form-field-how-to-require-an-input-format


![formfield](https://cloud.githubusercontent.com/assets/10223970/7043009/ba2eaf7a-ddab-11e4-8547-dce9bbb9b671.png)

**Comment by invokelocal** [comment]
maybe the "placeholder" code adds those "(   )   -    "

**Comment by invokelocal** [comment]
Looks Great!! You are the man! don't worry too much about the phone number at this time if its not done now... I need to sleep since it is 5AM for me, lol
