### ISSUE TITLE
Upgrade Form and Stripe

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#107]
I received a reply from intercom in regards to the Stripe issue, and basically it sounds like RevuCue needs to send the clients email address to Stripe in the initial payment data, and if that email address is the same as is on file with RevuCue then the data will combine as one within intercom....

So on the Upgrade page either program the clients address to be sent to Stripe without the client even seeing a form field (which would be best because in this way the client could not use a different email address than the one that they already entered to open the account)

Or make an addditional form field in the Upgrade page if needed that will be labeled 

"Your Log-In Email Address:"

And have that form field pre-populate the users email address and be sent to Stripe along with the users payment info.

And a quick and less important change to the Upgrade page, can you make the background were it says the plan names like "Local" / "Local+" or "Empire" red instead of the current blue.

And eliminate the "Credit Card" check box, as now without the PayPal option I do not think it is needed.

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Can you change the graphic behind the plan names from the current blue to a red color?

the form field label that says "Your Log-In Email Address:"

change it to say just: "Log-In Email:"   I think that will fit better into the space available.

Also will that now integrate the users email as their customer label in stripe?

**Comment by orientationsys** [comment]
Done ! Please check. You can reflash your page than you will see the new Graphic . Also the users email have integrated their customer label in stripe.

**Comment by orientationsys** [comment]
![qq 20150331103327](https://cloud.githubusercontent.com/assets/2968891/6911354/1203c8f4-d792-11e4-8110-42ffd1b2fd18.png)

**Comment by invokelocal** [comment]
sweet
