### ISSUE TITLE
All Outgoing Emails

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#108]
At the absolute bottom of all the emails that go out from RevuCue I would like you to include a line of text with a clickable link in it:

"Powered by RevuCue"

where the "RevuCue" is the clickable link that would take the recipient to revucue.com

include this text under all other email content, center it left to right within the email body and include it in all client to their customer emails, so all "Rate & Request" "Reward Emails" & "Last Chance Emails"  will have this along with all other automatic emails sent by RevuCue on behalf of the users.

**Comment by invokelocal** [comment]
Just delete the text in the out going emails that says:

"If you wish to contact us, please do not reply directly to this email, please send emails to the email address in the signature above. Thank You"

And replace it with:

"If you wish to contact us, please do not reply directly to this email, Powered By RevuCue"

and make the word "RevuCue" a link to revucue.com

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Nice
