### ISSUE TITLE
Chance Your Payment

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#112]
I clicked on Add Location, and had reached my plans limits, apop-up informed me I had to upgrade so I clicked on OK and the payment pop-up the title was "Chance Your Payments" this translation does not work lol, it makes it sound like gambling with your money, so can you change this title were ever it says chance your payments, change it to:

"Enter Your Payment Details"

and if possible I would rather the client not have to enter their payment information every time they want to add a user or location, I would rather the pop-up appear that now says:

"You have reached your plans limit of included locations and additional locations are an additional $19 per month"

for add location and the two buttons on the pop-up say "Cancel" & "Add Another Location For $19 per month" and if they click on cancel of course nothing will happen and the pop-up goes away, ad if they click on "Add Anot............." then they will be automatically charged for this additional feature without having to do anything else

**Comment by orientationsys** [comment]
I have some doubts about this. Becase The Local Plan Client or The Local Trial Plan Client  who clicked on Add Location will see the Upgrade Button and they must upgrade their plan to Local + or Empire so that they can buy a extra location . So now , it means The Local Plan Client or The Local Trial Plan also can buy  extra locations??

**Comment by invokelocal** [comment]
No the Local plan / Free Trial plan has to upgrade to Local+ or Empire to add locations or extra users, so in those plans they will have to Upgrade as it is now, but in the Local+ & Empire plans I would prefer that the ADMIN user simply click on Add Location (or Add User) and when it is beyond their included amounts that they simply click one button to confirm the additional monthly charge instead of having to go through the process of entering their payment information again for every addition. I believe Stripe has this capability...

**Comment by invokelocal** [comment]
So if a user that is signed up for the Local+ plan already has 5 users added and clicks on Add User for a 6th user a pop-up would appear and say:

"This user will be an additional $9 more per month, since it exceeds the included user amount in your current plan" 

below this text on the pop-up there will be two clickable buttons:

"CANCEL" & "I AGREE TO THE ADDITIONAL MONTHLY FEE"

if they click "CANCEL" the pop-up goes away and they don't get charged additional fee.

if they click "I AGREE TO THE ADDITIONAL MONTHLY FEE" then they will start to get billed that additional $9 monthly fee through stripe without having to re-enter their credit card information

after clicking on "I AGREE TO THE ADDITIONAL MONTHLY FEE" the pop-up will go away and they will be able to enter their information

same for the Add Location function.....

**Comment by orientationsys** [comment]
Done ! Please check
