### ISSUE TITLE
Video FAQ search

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#114]
on the page "http://revucue.com/admin/faq" I do not like the functionality of the search, I have two test FAQ videos up there and one is named "TRUCK" and if a user wanted to find this video they might type in "black truck" or "help with trucks" for example, and in the search engine that came with the theme, unless you type in exactly what the title is "TRUCK" the page will go blank and nothing will show, so what I would like to do if possible is to integrate a better search engine within this page so if the user types "trucks help" "truc" or anything else pertaining to this topic that this video will appear.

Let me know if this is an easy enough task to complete

**Comment by orientationsys** [comment]
Done ! Please check .

**Comment by invokelocal** [comment]
Sweet!!
