### ISSUE TITLE
Add New Customer Form Fields On Mobile

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#121]
Since all the changes to the form fields for the PC look, they look too small on the damn cell phone now, I did not mean to cause additional frustration for you but is there any way to expand the form fields on mobile? before they looked great on mobile, and bad on pc, and now they look good on pc but bad on mobile... maybe a "%" html ????

**Comment by invokelocal** [comment]
when I hold my mobile phone vertical the logo is wide enough but it makes the form fields too skinny, and when I hold my mobile phone horizontally, the form fields expand to the width of the logo which is a good width.......

**Comment by invokelocal** [comment]
This is how it looks with the mobile vertical, it makes the form fields too small for some reason:
![mobileskinny](https://cloud.githubusercontent.com/assets/10223970/7051075/30531f58-ddeb-11e4-9899-ede88fe5700e.png)

**Comment by invokelocal** [comment]
And this is how it looks horizontal, which is ok because the form fields expand to the width of the logo:

![horiv](https://cloud.githubusercontent.com/assets/10223970/7051119/7a5c556a-ddeb-11e4-8512-dcd59732ce58.png)

**Comment by orientationsys** [comment]
I have change some thing about this. So what about now webPage??

**Comment by invokelocal** [comment]
That is perfect! looks great on mobile, and on pc, and on PC. DONE!
