### ISSUE TITLE
Address Line 2

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#122]
in the add new customer form the form field "Address Line 2" within the field itself the text says "Address Line 1" as shown in the picture, change it to say:

"Address Line 2" in the Address Line 2 field

![adline1](https://cloud.githubusercontent.com/assets/10223970/7058857/332af088-de2d-11e4-82d2-8b93348fad9f.png)

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
sweet
