### ISSUE TITLE
Homepage Scaling

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#123]
attached is an example of what the homepage looks like in a smaller browser window like a small pc, tablet or phone. Can you code the title, and image / video to scale to size depending on what screen resolution is browsing it and make that home page "responsive" 

If this is difficult to code, I would rather make the homepage a wordpress site, like the /learn page and be able to use a responsive themed page.

Let me know which is easiest for you
![sizematters](https://cloud.githubusercontent.com/assets/10223970/7058932/1f3c1074-de2e-11e4-8c8b-eb747e8c5a1d.png)

**Comment by orientationsys** [comment]
I have change the webPage, Does it OK??

**Comment by invokelocal** [comment]
The video is better, but the image that is over the video is not scaling properly, so the image is getting cut off in some screen resolutions but after you click on it the video is fitting within the screeen, but it is much better than before
