### ISSUE TITLE
HOME Page Pricing Table

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#125]
The rows of the pricing table on the home page, enter this information:

 
FREE TRIAL
FREE for 30 days
Enter Up To 20 New Customers
1 User
1 Location
Phone Support
In-App Support

LOCAL
Up To 20 New Customers / Month
1 User
1 Location
Phone Support
In-App Support
CRM & Email Marketing

LOCAL+
Enter Unlimited New Customers
Up To 5 Users Included
1 Location Included
Phone & In-App Support
Additional Users $9 / Month
Additional Locations $19 / Month

EMPIRE
Enter Unlimited New Customers
Up To 20 Users Included
Up To 2 Locations Included
Phone & In-App Support
Additional Users $9 / Month
Additional Locations $19 / Month

**Comment by invokelocal** [comment]
On the Pricing Table the buttons currently say "Buy Now" change that to:

"Sign Up Now"

and have that link to:

http://revucue.com/user/create

but after they click "Create Account" it will go to the portal "Upgrade" page and the plan they clicked on will be selected in the Upgrade page, if they had clicked on Free Trial it will just go to the portal dashboard

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Everything is good on the tables, except you took out the prices that you had there....... 

In the headings were described below put the words below that are outside the ( ) into the pricing table:

FREE TRIAL (white font ot top)
 FREE (red font at top of table)

LOCAL (white font ot top)
$19 / MONTH (red font at top of table)

LOCAL+ (white font ot top)
$79 / MONTH (red font at top of table)

EMPIRE (white font ot top)
$179 / MONTH (red font at top of table)

**Comment by invokelocal** [comment]
CORRECTION******

In the headings were described below put the words below that are outside the ( ) into the pricing table:

FREE  (white font at top)
FREE TRIAL(red font at top of table)

$19 / MONTH (white font at top)
LOCAL (red font at top of table)

$79 / MONTH (white font at top)
LOCAL+ (red font at top of table)

$179 / MONTH (white font ot top)
EMPIRE (red font at top of table)

**Comment by invokelocal** [comment]
So the red names for the plans stays the same as you have them now, just change the white font heading of each table to reflect the monthly price

**Comment by orientationsys** [comment]
Done ! Please check
