### ISSUE TITLE
Free Trial sign ups...

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#126]
I saw today that when someone signs up for a free trial and creates their account after that they are directed to the upgrade page within the portal.

That is good for every plan except the free trial, the new user should be taken directly to the dashboard page within the portal first after initially signing up for the free trial only.

So free trial users got to the dashboard after creating account, and "Sign Up Now" new users who chose Local / Local+ or Empire plans go to the upgrade page as you have it now

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Sweet!!
