### ISSUE TITLE
New Integration

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#127]
I want to integrate a new program into revucue, and it only requires a simple code to be inserted above the < / body > tag

The code needs to be inserted on the page www.revucue.com for now and maybe other pages in the future.....

I will email you the word file as this site does not allow me to enter a word document onto it

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Thank you, can you put that on every page of the site that is not the actual program like, free30, how it works and any others...

**Comment by orientationsys** [comment]
Done ! Please check
