### ISSUE TITLE
Pop -ups..

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#129]
Is there anyway that you could copy and paste into here the messages that are in the green pop-ups after an action is done or all pop-ups of any color that you have programmed because I need to edit the spelling and wording of most of these but it is difficult to identify each of them within the program...

Let me know if this will work or of you have a better solution to edit these...

**Comment by orientationsys** [comment]
All those messages are generated within the model level so it's difficult for me to copy/paste all of them here, I think you have to check them one by one and make a list so I can update them one by one, thanks.

**Comment by invokelocal** [comment]
Ok, i will
