### ISSUE TITLE
Customer Info Pop-up

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#13]
In the CUSTOMER INFO pop-up in the EXISTING CUSTOMERS table the long "Notes:" of some customers are still running off the pop-up like the reviews used to.

If possible format this so that the text does not run off the pop-up

**Comment by orientationsys** [comment]
I do not see "Notes" run off the pop-up?can you Screenshot about it

**Comment by invokelocal** [comment]
![runnoff](https://cloud.githubusercontent.com/assets/10223970/6202477/a5528d68-b4b3-11e4-82d3-a91cead59b07.jpg)

**Comment by orientationsys** [comment]
Done!please check

**Comment by invokelocal** [comment]
AWESOME!!
