### ISSUE TITLE
Contact Us Area at the bottom of the home page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#134]
Leave the text:

"Contact Us"

delete the text:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur eros dolor,
sed bibendum turpis luctus eget"

replace the text that says: "If you have a project you would like to discuss, get in touch with us."
and make it say: "Email or call us anytime and we will respond as soon as possible."

delete the text that says: "Morbi interdum mollis sapien. Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, lectus arcu pulvinar risus, vitae facilisis libero dolor a purus."

were it says: 

"SeanTheme Studio, Inc
795 Folsom Ave, Suite 600
San Francisco, CA 94107
P: (123) 456-7890
+11 (0) 123 456 78
seanthemes@support.com"

change that to say:
"Invoke Local LLC
1-855-REVU-CUE
1-855-738-8283
invokelocal@gmail.com"

and make the emails for the form go to:

invokelocal@gmail.com

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
It looks good, but I did a test email in the contact form about 5 minutes ago and haven't gotten the email yet

**Comment by orientationsys** [comment]
You can try again. I get the email , Now I change the email address to invokelocal@gmail.com
