### ISSUE TITLE
ISSUE**

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#139]
A new test customer entered over 300 contacts into the import function, the emails all went out, but the link in the email did not work. He says the link did not redirect the recipients to the rating page.

This may be an issue with the import funtion as it relates to sending and coding the emails I do not know, but can you make this prioity to fix this issue?

**Comment by invokelocal** [comment]
the test client who had the issue was nashvillemixedmartialarts@gmail.com is there any way you can easily resend the emails that he imported (374 imported emails in total)? I do not know how else to resend to that large amount of customers other than one at a time through the existing customers table.

Unless you can to make a "BULK EMAIL" button on the top of the EXISTING CUSTOMERS table which would allow a user to click bulk email button and all the customers shown in the table at the time would get a email, the heading of the pop-up would say:

"This allows you to send a bulk email to all the customers shown in the current table view."

under the heading the user being able to choose from:

"EMAIL THESE CUSTOMERS" with the same form fields as the other email pop up, or 

"SEND CUSTOM RATING REQUEST EMAILS" 

all the form fields in the other email pop-up would be available in this pop-up .... so they could edit the outgoing message and click:

"SEND"

and all the customers visible on the table would get the email

**Comment by invokelocal** [comment]
If you need me to add time to make the BULK EMAIL function let me know. Thanks

**Comment by invokelocal** [comment]
Here is a visual with the new button added:

![bulkemail](https://cloud.githubusercontent.com/assets/10223970/7216108/57fc334e-e5b8-11e4-99eb-a63e0f46836e.png)

**Comment by orientationsys** [comment]
I just test the process. For example , my test user email is lz@orientationsys.com . When I import a customer and set the Estimated Date . And when the corn.job have carried out , I received an email about 3 Option ,like the blow image.

**Comment by orientationsys** [comment]
![qq 20150418001728](https://cloud.githubusercontent.com/assets/2968891/7216199/7ae0a496-e629-11e4-911d-81437c58ae99.png)

**Comment by orientationsys** [comment]
Then I click the Yes button, and my customer email address received the Rate Email and the rate link work well . So I am confuse . Because of the customer data from +ADD NEW CUSTOMER or import csv file they have the same email template.

**Comment by invokelocal** [comment]
I do not know if they imported the information correct? 

But they did enter a large number of email addresses at once,  I do not know if that would cause a problem? 

Go ahead and look in their account if that will help to solve the issue...

He told me that his email was on the list and he received the email but the link did not work, and I believe this because the LeadDyno.com script that you integrated into the site tracks all people who go on different pages also and I see alot of people going to the rate web page but see no new rating in the test users account

**Comment by invokelocal** [comment]
Also a new issue I just thought of when customer imports customer list and picks future date to send rate and request email, they should not be asked if they want to send to each one, because they might enter in 10 or 100 or 1000 and I do not want the user to get 1000 emails in one day asking if they want to send the rate & review emails....

So if there is a way to not give an option to send in the future * ONLY FOR IMPORTED DATA * (so you keep the future date functionality working when they enter individual new customers) so if you import data all the customers will receive Rate & Review emails immediately

**Comment by invokelocal** [comment]
I think I know what happened now with this issue with the customer, he received the email asking if he wanted to send the emails "Yes" "No" "Future Date" and he didn't realize that there were 371 more questions below the top one all in the same email, so I do not think there was an issue with functionality but there is an issue with user interface which needs to be changed which I will address in a new issue
