### ISSUE TITLE
Contact Support

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#14]
Make the form background the image "service-support.jpg" which I will send to you, allowing the girls face in the picture to be seen to the right of the form fields.

On the left side of the form image will be the location of the contact form.

Delete the blue "warning"

Make the heading of the form say:
"CALL RevuCue at 1-855-REVU-CUE  (1-855-738-8283) or email us anytime with the form below:"

There should be 4 form fields:

"LOG-IN EMAIL ADDRESS"
"NAME"
"CONTACT PHONE NUMBER"
"MESSAGE"

**Comment by invokelocal** [comment]
![service-support](https://cloud.githubusercontent.com/assets/10223970/6202106/b94f3664-b499-11e4-96cb-dd4248883e44.jpg)

**Comment by orientationsys** [comment]
Done!please check

**Comment by invokelocal** [comment]
the word "CALL" in the heading should be "Call" 
The form field label "LOG-IN EMAIL ADDRESS" should be "Log-in Email Address"
The form field label "NAME" should be "Name"
The form field label "CONTACT PHONE NUMBER" should be "Contact Phone Number"

Is it possible to have the page look like this:
![serviceform](https://cloud.githubusercontent.com/assets/10223970/6202621/6c62e950-b4bb-11e4-980d-9684699eea85.jpg)

**Comment by invokelocal** [comment]
The form is inside of the picture which looks better

**Comment by orientationsys** [comment]
done !please check

**Comment by invokelocal** [comment]
this is how my screen looks below, the girls face is overlapped by the form and it is not centered, so for now just delete the photo and if you can make the Message form field larger like you had it originally and it will be good

![myscreen](https://cloud.githubusercontent.com/assets/10223970/6202727/f3f73322-b4bf-11e4-9433-73a915f8c8c0.jpg)

**Comment by orientationsys** [comment]
done!please check
