### ISSUE TITLE
Phone Number Field

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#140]
In the phone number form field you have added some type of restriction to the field and it does not allow me to enter in phone numbers.... 

So every time I am getting this error message shown in the form, and it deletes all the info I had input. Here is a screen shot of the error, please allow it to accept as it did before:

![numissue](https://cloud.githubusercontent.com/assets/10223970/7216145/4fa56704-e5ba-11e4-9711-dd1feb69424b.png)

**Comment by invokelocal** [comment]
The error says: "phone number is invalid. The correct number like this 111-222-3333!"

**Comment by orientationsys** [comment]
I have cancled the Phone Number Field restriction . Done ! Please check

**Comment by invokelocal** [comment]
Sweet!
