### ISSUE TITLE
RevuCue Emails to Clients

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#15]
Can you format all the outgoing emails from RevuCue which would include the register email, rating request emails, and any other emails in the future that go from RevuCue to the users / clients

There should be a header at the top of the emails (just like the clients emails that are sent to their customers) black in color with the RevuCue logo centered in it

For RevuCue's signature under the body of the email it will say:
"Thank You,"
Also include the phone number:
"1-855-REVU-CUE" 
And a link to contact support, this link will take the email recipient to a "CONTACT SUPPORT" page even if they are not signed into their portal and in the signature the link will be a button with the text:
"CONTACT SUPPORT"

**Comment by orientationsys** [comment]
Done! Please check
