### ISSUE TITLE
Rating Request Email Sent To Clients

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#16]
Make the following changes to the Rating Request Verification Email that gets sent from RevuCue to the clients asking if they want to send the email to their customer yet(it should also be formatted to include a black header and the RevuCue logo and signiture as stated on a different issue):

The title of the email should change from "Verification Email" to:
"Send this customer a Rating Request Email now?"

Now it says: "Hi![users'_name]", I want to delete the "Hi!" and it will be the "[users'_name]" only

2 lines down from the clients name it should say:
"DO YOU WANT TO SEND THIS CUSTOMER A RATING REQUEST EMAIL?"

Under that it should say:
"CUSTOMERS NAME: [customer_name]"
"CUSTOMERS PHONE NUMBER: [customers_phonenumber]"
"CUSTOMERS EMAIL: [customers_email]"
"NOTES:[notes]"

Then the links should say the following with a space in between each group as it appears below:
"Clicking YES will send the email immediately."
"YES" (link)

Clicking NO will never send a Rating Request email."
"NO" (link)

"Clicking FUTURE DATE will allow you to pick a future date to send the Rating Request."
"FUTURE DATE" (link)

**Comment by orientationsys** [comment]
Done !Please check

**Comment by invokelocal** [comment]
can you add the text "Send this customer a Rating Request Email now?" under the clients name, so it would look like:

[RevuCue Logo]

[Clients Name]
[space]
Send this customer a Rating Request Email now?
[space]
[Customer info]

**Comment by invokelocal** [comment]
In the clients name add a "space" in between their first and last name.

below the "FUTURE DATE" link add two spaces before the signature

**Comment by orientationsys** [comment]
Done! Please check
