### ISSUE TITLE
Export CSV issue

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#17]
when I try to export data from the EXISTING CUSTOMER table, and there are rows that have ratings then a row with no customer rating, sometimes the exported file stops exporting data at the row that has no star rating.

For example: the first 3 rows have customers who rated 4 stars each, then the 4th row that customer did not rate, then the following rows have customers who rated different star amounts. The exported csv file will stop at row 3, and all of the following rows will not be in the exported file. If I rearrange the data and export it, the data will again stop sometimes at the row with no rating???? and other ways that I arrange the data it will all export within the csv file.

I do not have any suggestions as to why I think this is happening

**Comment by orientationsys** [comment]
Done!Please check

**Comment by invokelocal** [comment]
AWESOME!!
