### ISSUE TITLE
Page Headings

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#18]
The following page headings need t be converted to all capitol letters:

"Change Password:" change this heading to "CHANGE PASSWORD:"

VIDEO FAQ'S page heading is currently "Search Results" change to "VIDEO FAQ'S"

COMPANY PROFILE page current heading is "EDIT COMPANY PROFILEyou can update company logo!" change it to "COMPANY PROFILE"

ADD LOCATION page heading now is "Add Location you can add a branch location" change to "ADD LOCATION"

REVIEW LINKS page currently has a heading of "Review Links (and sentences)" change it to "REVIEW LINKS (keep the sentences that follow)"

USER REPORTS page it currently says "Reports" change the heading to "USER REPORTS"

ADD / DELETE USERS page current heading is ""Add Or Delete Users" change to "ADD OR DELETE USERS"

**Comment by orientationsys** [comment]
done !please check

**Comment by invokelocal** [comment]
On the REVIEW LINKS page when I said (keep the sentences that follow) I do not want you to type in the words (keep the sentences that follow) it simply means do not change what was there to begin with, so can you please put back the sentences that were already there explaining the functionality of this page

**Comment by orientationsys** [comment]
done!please check

**Comment by invokelocal** [comment]
can you delete the "(" & ")" at the beginning and end of the sentences

**Comment by orientationsys** [comment]
Done!please check
