### ISSUE TITLE
Icons for the menu bar / column

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#19]
Below are the icons from within the theme (UI Elements - Icons - Web Application Icon table) that I would like to the left of the menu bar buttons to replace the existing icon next to each:

DASHBOARD: fa-bar-chart-o

CUSTOMERS: fa-star-o

PROFILE: fa-sign-in

SETUP WIZARD: fa-majic

HELP: fa-plus-square

COMPANY: fa-map-maker

R&R SETTINGS: fa-cogs

USERS: fa-user

**Comment by orientationsys** [comment]
done! please check

**Comment by orientationsys** [comment]
i can not find the fa-majic in the theme?so ,where is it???
