### ISSUE TITLE
Email Percentages

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#2]
On the EMAIL TEMPLATES page
The columns Click Through Percentage & Open Percentage are calculating the incorrect things.
They currently calculate the percentage that each email is used.
I want these fields to represent the percentage of time each type of email was clicked on or opened by the customer.
An example: I create a RATING REQUEST EMAIL named "RATE" and I send it to 100 customers and 78 of my customers click on the link in the body of that email, so my "Click Through Percentage" should be 78% and this number has nothing to do with any other email theme, the same goes for "Open Percentage" an example a "REWARD EMAIL" I name "REWARD" goes out to 100 customers after they rated their experience and 82 customers opened that reward email, so the column should say 82% and have nothing to do with the other reward emails

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
AWESOME!!
