### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#20]
The pictures that are uploaded to the server with the CKeditor in the "Body" form fields of the email template form are not showing up on the emails, (maybe the temporary image location on the server issue??) so if this function can not work properly just go back to a basic form field to enter text.

after I click preview on one of the saved templates the webpage says: "email have send!Please check your email for the preview." change it to: "Please check your email for the preview."

I click "eddit" button on the EMAIL TEMPLATES page to edit a theme, and there are 2 buttons at the bittom of this form, Update & Cancel. After the user clicks on "Update" the browser should be redirected to: http://revucue.com/admin/ratingrequest

**Comment by orientationsys** [comment]
Now,you can Receive the image in the email,but,you need to reupload the image in ratingrequest Page.In the existingcustomer page,I need some time to Solve the Ckeditor problem

**Comment by invokelocal** [comment]
do not worry about the Existing customer page right now

**Comment by invokelocal** [comment]
But in the EXISTING CUSTOMER table when you click on a email address in the body area of the form the text looks like this 

"<p>We value your opinion, click the link below to rate your experience with&nbsp;us and receive a discount offer by email:</p>"

With the HTML tags??????

**Comment by orientationsys** [comment]
Because of the Ckeditor,when we save some data with it, It will Automatic around the data with some html tags
