### ISSUE TITLE
Button Normalization

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#21]
Below are small fixes to the buttons and some final heading issues:

on the dashboard page "+Add New Customer" button should look like: "+ADD NEW CUSTOMER"

on change password page, on the heading delete the ":" so it looks like: "CHANGE PASSWORD" the current "Update" button should look like "UPDATE"

video faq's page, the "Search" button should be red and look like this: "SEARCH"

on the CONTACT SUPPORT page the title of the form should be centered, and the "Send Message" button should look like "SEND MESSAGE"

on the company profile page the title "Preview" should look like "PREVIEW", in the COMPANY PROFILE form the field title "Company Logo" should look like "COMPANY LOGO" the form field "Company Name" should look like "COMPANY NAME" and the " * " should be deleted from the 3 color selector form field titles

on the add location page the button that says "Add Location" should look like "ADD LOCATION" & the table column headings should be "ADDRESS LINE 1" - "ADDRESS LINE 2" - "CITY" - "STATE" - "ZIP CODE" - "OPERATION"

on the form elements page, the heading should look like this:
"FORM ELEMENTS: Customize your "Add New Customer Form" by turning ON or OFF each of the below form elements."
on the table the word "Title" should look like "TITLE", the description for city should be "Customers City", the description for state should be "Customers State"

on the rate webpage the first heading should be:
"RATING WEBPAGE TITLE: This will be the title your customers see above your star rating selector." , the title of the first form field should be "RATING TITLE" the buttons text should be "UPDATE" & "PREVIEW" when you click update button the message should say "Success! you have updated the RATING WEBPAGE TITLE!"
the 2nd heading should be "INTERNAL REVIEW FORM TITLE: This will be the title of the review form your customers will see if they rate their experience 1-3 stars." the title of the form field should be "INTERNAL REVIEW FORM TITLE"  the buttons text should be "UPDATE" & "PREVIEW", when you click update button the message should say "Success! you have updated the INTERNAL REVIEW FORM TITLE!"

on the review links page the "Add Link" button should look like this: "ADD LINK" , the "Operation" column should look like "OPERATION", and the clickable links in that column should look like: 
"Edit | Delete"

on the email templates page, the first heading should look like this:
"RATING REQUEST EMAIL: This email asks your customers to rate their experience with your company, and for doing so they will receive a follow up email with an incentive or simple thank you from you."
the "Add Themes" button should look like: "ADD THEME", and the headings of the columns should be: "EMAIL NAME" - "CLICK THROUGH %" - "FROM NAME" - "FROM EMAIL" - "SUBJECT" - "BODY TEXT" - "STATE" - "OPERATION" & in this table take out the "Search" function at the top, the other tables do not have this function
the second table heading should look like this:
"REWARD EMAIL: This email is a follow up email that is sent automatically to your customer after they rate their experience, it can be a simple Thank You or an incentive like a coupon or discount."
the "Add Themes" button should look like: "ADD THEME", and the headings of the columns should be: "EMAIL NAME" - "OPEN %" - "FROM NAME" - "FROM EMAIL" - "SUBJECT" - "BODY TEXT" - "STATE" - "OPERATION"
the third table heading should look like this:
"LAST CHANCE EMAIL: This email has the same function of the Rating Request Email and is sent to your customer automatically 7 days after the Rating Request Email if your customer has not yet rated their experience."
the "Add Themes" button should look like: "ADD THEME", and the headings of the columns should be: "EMAIL NAME" - "CLICK THROUGH %" - "FROM NAME" - "FROM EMAIL" - "SUBJECT" - "BODY TEXT" - "STATE" - "OPERATION"

on the add or delete users page, the button text should be "ADD USER" & in the OPERATION column the links should look like this: "Edit | Delete"

**Comment by orientationsys** [comment]
Done !please check

**Comment by invokelocal** [comment]
on the review links page make the heading bold like you did with the other headings, it should say: "REVIEW LINKS: These are web addresses your customers will be directed to when they rate their experience between 4-5 stars. RevuCue will randomize these links. Paste web addresses that are the exact pages your company can be reviewed on."

on the email templates page, the first and third buttons say "ADD THEMES" they should say "ADD THEME" with no "S"

**Comment by orientationsys** [comment]
Done !Please check
