### ISSUE TITLE
Add / delete users

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#24]
In the Add / Delete Users page the ADMIN LEVEL user should not be allowed to be deleted, that user should show up in the table so it can be edited but when user clicks delete a pop-up should come up that says "ADMINISTRATOR LEVEL USER CAN NOT BE DELETED"

**Comment by orientationsys** [comment]
Done, Please Check!

**Comment by invokelocal** [comment]
This function is not working on my browser, when I click on delete for the admin level user in the table on the ADD OR DELETE USERS page a pop-up comes up asking me if I want to delete this data......

**Comment by orientationsys** [comment]
Done! Please Check
