### ISSUE TITLE
30 days free

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#28]
I would like you to create a page that will be used in the future but for now I would like the address: revucue.com/free30 created. this webpage will end up being a page were a new customer can sign up and get a 30 day initial free trial, I want the page at least created with no content for now so I can put it on business cards and by the time I use the cards you will have programmed the functionality of the page

**Comment by orientationsys** [comment]
Done ! the address is revucue.com/free30/index

**Comment by invokelocal** [comment]
nice
