### ISSUE TITLE
Form Elements Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#3]
The title of this page should be:
"FORM ELEMENTS: Customize your Add New Customer form by turning ON or OFF each of the below form elements."

The form field after the word Title: should be longer so the client can see a longer title if entered.

When the client clicks on the "Update Form" button at the bottom, a "Add New Customer Form" preview should pop up

**Comment by orientationsys** [comment]
Done!Please check

**Comment by invokelocal** [comment]
Two issues with the fix:
#1: the logo on the page is very large and does not scale to size like the Add New Customer webpage.
#2: it would be better as a new browser window that I can close, right now there is no way for me to close the pop-up so it is taking up my entire screen with no way to close it

**Comment by orientationsys** [comment]
Done please check.I have add a preview button.

**Comment by invokelocal** [comment]
looks great! except the "Preview" button needs to be in capitol letters like: "PREVIEW"
