### ISSUE TITLE
Buttons in Emails

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#31]
I just got a "scheduled email" from RevuCue and I see the nice formatting you did on the layout.

where it says "CONTACT SUPPORT" in the signature, it is a button.

Can you make the "YES" - "NO" - "FUTURE DATE" in this email buttons also?

and can you make the rating link within rating request emails a button like this support button?

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
on the rating request email the button should say "CLICK HERE TO RATE"

and if possible the cursor will change on mouse over, as of right now when you go over the button the cursor does not change, so sme people might not know it is clickable

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
sweet!!!!!!
