### ISSUE TITLE
Create Simple Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#32]
I would like you to create a simple page if possible, the address:

revucue.com/howitworks

This page only has one video in the center of it, about the size of a youtube video, and if possible through my "super admin" log in I could upload a video to this page in the same way as you have set up for the VIDEO FAQ'S

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
can you make the url:

revucue.com/howitworks

with an "s" on the end, the current url has no "s" on the end

**Comment by orientationsys** [comment]
Done! Please check
