### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#33]
for RevuCue.com/free30/index, do I need to include the "/index" on the end of the URL? or will RevuCue.com/free30 direct the browser to the same place?

**Comment by orientationsys** [comment]
May be i can user Revucue.com/admin/free30 replace it? Becase of the Url composition is "hostlocal/Controller(name)/Action(name)"

**Comment by invokelocal** [comment]
no, I do not want the person who goes there to have to be a user of revucue, the extra pages will be for sales purposes

I want the web address to be short, so I do not want to add any extra text at all

**Comment by invokelocal** [comment]
when I type in revucue.com/free30 in my browser it takes me to the same page as revucue.com/free30/index, so I know it works I just was asking a technical question.

just leave the url as you had it
