### ISSUE TITLE
File Size Issue!!!!!!!!!!!!

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#34]
I went to a business today to set them up on the trial of the application and first the paypal was left in Chinese language, but the big issue was the file size of their logo caused a major error in the application that returned the following error:

"Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 77000 bytes) in /home1/revucue/public_html/protected/models/Image.php on line 116"

I believe this error is because of the file size, and it would not allow the pre-portal to load or the company profile so at first I could not access the portal at all.

I would like the file upload in the registration to be the one step "Choose File" button and somehow have the application or database compensate for larger file sizes

**Comment by invokelocal** [comment]
I went into the PHPmyAdmin and changes the image source in the database, and the issue was solved for that client but we need to code in a way that only usable file sizes will be accepted

**Comment by orientationsys** [comment]
Done! Please check! I have limit the size about image size!

**Comment by invokelocal** [comment]
Great, it works!
