### ISSUE TITLE
Tablet Issue!!

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#36]
On an Android tablet the "Add New Customer Form" continuously re-loads. Meaning that when I go to that page every 2 seconds it automatically reloads, continuously on the tablet. So if I try to enter data the page will reload before I am able to complete the entry and hit submit.

**Comment by invokelocal** [comment]
the tablets browser is: Android version 4.4.2 "KitKat

**Comment by orientationsys** [comment]
Done! Please Check!

**Comment by invokelocal** [comment]
looks good
