### ISSUE TITLE
SSL Logo

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#37]
I enabled SSL on the site, and below is the logo for the SSL certificate, add it to the footer

<a href="https://www.positivessl.com" style="font-family: arial; font-size: 10px; color: #212121; text-decoration: none;"><img src="https://www.positivessl.com/images-new/PositiveSSL_tl_trans2.png" alt="SSL Certificate" title="SSL Certificate" border="0" /></a>

**Comment by invokelocal** [comment]
there is html for this logo, it read the html in the comment above and displayed the picture

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
cool
