### ISSUE TITLE
SPAM filter issues

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#38]
All mail is now going to spam, I have enabled the SPF & DKIM from inside the control panel and asked host gator to start a PTR request on the domains' IP. The PTR will take a few days to initiate and maybe that will resolve the problem but the current host IP was on a blacklist, the server is a shared server and whoever else uses it could have caused this to happen. 

Question for you: Should I swithch my hosting to VPN or a Dedicated server?

Or are there ways to program the emails s that they are more compliant with email hosts, like more information in the headers or how the emails get routed???

Please let me know what can be done to eliminate the possibility that the emails go to spam

**Comment by invokelocal** [comment]
I have noticed that emails that are coming from "RevuCue.com - admin@revucue.com via gator4176.hostgator.com " are not getting sent to spam, that is going into my Primary Inbox.

This is still getting routed through the same servers / IP address but it is coming from "admin@revucue.com" and it is making it into my primary inbox.

I was wondering if we allowed the client to choose the name of who the email is from as you have it now "Who Is This Email From?" but we deleted the form fields that allow them to put in their own email address. 

So for example a user named "Tim Smith" would enter his name in the email form as it is now but the email would appear from "Tim Smith - admin@revucue.com via gator4176.hostgator.com "

We would just have to include a disclaimer under the email signature in each email that would say  "If you wish to contact us, please do not reply directly to this email, please send emails to the email address in the signature above. Thank you."

I have created the email address "admin@revucue.com" so it is now a real email address which should help future emails stay out of spam folder also

**Comment by invokelocal** [comment]
Gmail, emailed me to say an app tried to access revucue@gmail.com and it denied access, so I changed the security settings to allow the "app" to have access to the email, so if you were having issues because of the security settings hopefully this has solved the problems

**Comment by invokelocal** [comment]
Here is where you need to go within HostGator CPanel to make any changes to the email server settings, it is under "Email Authentification"

![hg2](https://cloud.githubusercontent.com/assets/10223970/6386574/8f4d8abe-bd40-11e4-8f1c-0663bd9a61fd.png)

**Comment by invokelocal** [comment]
![hg1](https://cloud.githubusercontent.com/assets/10223970/6386575/95738484-bd40-11e4-9dba-7b9755552103.png)

**Comment by invokelocal** [comment]
I enabled some things on here and made modifications a few days ago while on the phone with Host Gator support but check this out and see if the issue is within these settings

**Comment by orientationsys** [comment]
done! Please check

**Comment by invokelocal** [comment]
I wish man, but it is still going directly to spam folder

**Comment by invokelocal** [comment]
One big difference in the emails, the ones that send from revucue to client use the themes' email template I think, ???? and the other ones do not maybe try using the template for all emails

**Comment by invokelocal** [comment]
when the email is in the spam folder a info block says "Why is this message spam? It contains content that's typically used in spam messages." so maybe the interpreted content is making it go to spam folder

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
!!!!!!!!!!!VICTORY!!!!!!!!!!!!!!!!!
