### ISSUE TITLE
Existing Customers Table

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#39]
On the Existing customers table as of now when you first log in it shows the oldest customer entry at the top by default, I would like to change the default to show the most recent customer entered first at the top of the table, so the most recent date would be at the top and chronologically descending after that.

Also the page needs a title, above the buttons and table title the page "EXISTING CUSTOMERS"

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Can you put the heading "EXISTING CUSTOMERS" above the buttons and to the left in the same font, size, as the other headings

And the buttons would go back where they were

**Comment by orientationsys** [comment]
Done ! Please check
