### ISSUE TITLE
"Send this customer a Rating Request Email now?" email

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#40]
the "Send this customer a Rating Request Email now?" email should be titled "Send this customer a Rating Request Email now?", right now it is titled "Rating Request Email" please change the title.

Also after selecting a "FUTURE DATE" in the first email for a customer, the next email I was sent says "It is the last email to remind you to operation!" in red under my name, I want to delete this message and also I do not want to put a limit on how many times a user can choose a new future date.

So it might take 5 estimated future dates for a user to finish work for their customer so I want to allow the user to select as many future dates as they deem necessary

**Comment by orientationsys** [comment]
Done! Please check
