### ISSUE TITLE
IE bug

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#42]
in IE, under R&R Settings - Rate Webpage - Internal Review Form Title - PREVIEW button 
after I click preview the review form field is distorted and has a glitch as seen below

![image](https://cloud.githubusercontent.com/assets/10223970/6363280/71d93490-bc5c-11e4-8b0d-345566efe163.png)

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
Still has the same issue, no change in IE

**Comment by orientationsys** [comment]
![Uploading QQ截图20150226120235.png . . .]()

**Comment by orientationsys** [comment]
![qq 20150226120447](https://cloud.githubusercontent.com/assets/2968891/6386187/2709c02e-bdb0-11e4-8ca0-93ca86ae99d6.png)

**Comment by orientationsys** [comment]
what about your IE brower version?

**Comment by invokelocal** [comment]
![screen](https://cloud.githubusercontent.com/assets/10223970/6386276/f52d1e76-bd3b-11e4-824d-fed51dd68bf9.png)

**Comment by invokelocal** [comment]
![screen](https://cloud.githubusercontent.com/assets/10223970/6386293/2ac5628c-bd3c-11e4-95cc-2090e109d558.png)

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
Awesome!! I knew you would figure it out
