### ISSUE TITLE
Constant Loading Issue

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#43]
I just noticed in my Chrome browser on the PC even the front end website shows it as constantly loading on the tab at the top

**Comment by orientationsys** [comment]
can you screenshot the bug in your Chrome browser, in my Chrome browser i do not find the bug which "constantly loading on the tab at the top"?

**Comment by invokelocal** [comment]
after I deleted the cookies this issue stopped, but with the cookies deleted in Chrome, the favicon did not show in the tab. But the constant reloading was in the tab area of the chrome browser, the"loading circle" kept spinning in the place were the favicon usually loads
