### ISSUE TITLE
Intercom.io Script

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#44]
<script>
  window.intercomSettings = {
    // TODO: The current logged in user's full name
    name: "<?php echo $user->name; ?>",
    // TODO: The current logged in user's email address.
    email: "<?php echo $user->email; ?>",
    // TODO: The current logged in user's sign-up date as a Unix timestamp.
    created_at: <?php echo strtotime($user->created_at); ?>,
    app_id: "m3pysliz"
  };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/m3pysliz';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

**Comment by invokelocal** [comment]
I sent the script to you in a word document, to your email

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Nice!!!
