### ISSUE TITLE
Pricing Structure

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#47]
After doing some further research and getting some good advice from successful SaaS business owners I want to make some changes to the pricing structure.

There will be changes to the registration process as well but for this issue I will concentrate on the pricing structure.

Still 3 tiers of pricing, in addition to the free "30 day trial".
I will expand on the 30 day trial later.
The per month amounts have changed and also the $19 plan only allows 20 new customers per month to be entered, see below.

The 3 tiers should be priced as follows:

Tier 1, Name: LOCAL
Per Month Cost: $19
Included # Of New Customers: Maximum 20 New Customers Added per month (When limit is reached they must upgrade to add more customers within that billing cycle)
Number Of Included Users: 1 (Must upgrade plan to add more)
Number Of Included Locations: 1 (Must upgrade plan to add more)

Tier 2, Name: LOCAL +
Per Month Cost: $79
Included # Of New Customers: Unlimited New Customers
Number Of Included Users:  Up To 5 
Cost Of Additional Users: $9 / additional user per month
Number Of Included Locations:  Up To 1 
Cost Of Additional Location: $19 / additional location per month

Tier 3, Name: EMPIRE
Per Month Cost: $179
Included # Of New Customers: Unlimited New Customers
Number Of Included Users: Up To 20
Cost Of Additional Users: $9 / additional user per month
Number Of Locations: Up To 2
Cost Of Additional Location: $19 / additional location per month

**Comment by orientationsys** [comment]
the number of included Users it means there a adminLevel user and a userLevel user about the Tier1??

**Comment by invokelocal** [comment]
Tier 1 only has an ADMIN LEVEL user, so it is good for a small business who has no employees and does the work themselves, So all of the "User Counts" the ADMIN LEVEL user is the first user, so Local plan has only 1 ADMIN LEVEL user, and the Local+ plan has ADMIN LEVEL user plus up to 4 additional users within the plan

**Comment by orientationsys** [comment]
I am understand!

**Comment by invokelocal** [comment]
The "FREE 30 DAY TRIAL" plan will be the Local plan, so it will be FREE for 30 days, but be restricted to the 20 new customers added within the 30 days, so if the client tries to add more than 20 new customers they would have to pay for one of the 3 plans to continue and that would reset the customer count for the billing cycle, even if it was within 6 days of signing up, so which ever comes first, 20 new customers or 30 days the client would have to enter payment information and sign up for a plan

I will add a separate issue for the FREE TRIAL but I wanted to add this comment to make you aware that it is going to be created

**Comment by orientationsys** [comment]
Done! Please check
