### ISSUE TITLE
PrePortal Design

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#48]
The layout of the Pre-Portal page can be inproved and below I have a .png to show what I think it should look like. The "Welcome" text is deleted, the background is the same picture as in the log-in page. Most importantly the size of the buttons are more compact and the logo is closer to the buttons, the Fonts of the buttons are large and the colors are what the client had set up in their portal:

![newpre](https://cloud.githubusercontent.com/assets/10223970/6387049/d08a3834-bd49-11e4-9e7d-f0fef0fb5828.png)

**Comment by invokelocal** [comment]
.

**Comment by invokelocal** [comment]
The background color like in the Log-in background color can be semi-transparent, so the color would be set by the client for the background, button, and text and the background color would be semi-transparent like the screen shot below:

![bgg](https://cloud.githubusercontent.com/assets/10223970/6387132/379f6548-bd4b-11e4-8838-1f071cb02e83.png)

**Comment by orientationsys** [comment]
Done ! Please check
