### ISSUE TITLE
Submit new customer message

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#49]
On the Add New Customer page after the user clicks submit, there are two text messages that appear:
"email have send" in the upper left corner, delete this message
& 
"email send success!" in the top / middle of the form. this message should say "Email Sent!" and disappear after 3 seconds. if you can not put a time-frame on it to disappear just delete it, this is because if the customer is entering their info and the next customer comes along it might confuse the customer that has not put in information yet

**Comment by orientationsys** [comment]
Done! Please check. I have delete it

**Comment by invokelocal** [comment]
"email have send" is still in the upper left corner after you click submit

**Comment by orientationsys** [comment]
Done ! Please check
