### ISSUE TITLE
Video FAQ's creator

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#5]
In the Super Admin log in were I can add videos and the text and description there needs to either be a place where I can upload an image to replace the standard one that is shown, or if you can allow me to just embed a youtube video in the place of the photo.

**Comment by orientationsys** [comment]
Done!please check

**Comment by invokelocal** [comment]
Can you make it an option to upload a video onto the RevuCue server or option 2 I could simply provide a YouTube URL to the video instead of uploading it

**Comment by invokelocal** [comment]
The more I look at this webpage the more I think the pictures should have a frame around them that looks like a video player, It might not be obvious to the client that these are actually videos when they are just pictures, I could edit each uploaded picture to look like it is in a media player also...
