### ISSUE TITLE
Remove Formatting

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#50]
Can you remove the border formatting of the logos like seen in the picture below, so you would delete the formatting that put a white reflection below the logo and rounds the corners, keep the aspect ratio formatting but delete the other style formatting:

![remove](https://cloud.githubusercontent.com/assets/10223970/6387305/e470ee6a-bd4e-11e4-8be6-cdc49e66ead9.png)

**Comment by orientationsys** [comment]
Done! Please check
