### ISSUE TITLE
New Customer Form Formatting

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#52]
Please refer to the pic below to make the following changes:

More space between the title and the form.
Remove the "Portal" button and make the Logo a button and go to: "http://revucue.com/site/login"
Move the checkbox below the "Estimated Date" field and label it "Send Immediately"

![formmod](https://cloud.githubusercontent.com/assets/10223970/6387932/f2fc2f58-bd58-11e4-8bf8-4dee3229a442.png)

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
everything is good but I wanted more space under the title, not under the logo. If you can move the log back where it was but add a couple spaces under the heading / title

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
If you can refer to the picture, from where you have it now I am guessing: add 1 space above the logo, remove 1 space below the logo, remove 1 space below the title

**Comment by orientationsys** [comment]
Done! Please check
