### ISSUE TITLE
Dashboard Graphs

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#53]
I want these charts to stay simple but the first graph the label for the red now says "companys average star rating" change that to "Company" the label for the grey now says "signed in user rating" change it to say "You"

I would like this to gather "average star rating" data on a daily basis and display the past 12 months in the chart, so if possible this graph would be labeled with the months as you have it now but to the left would be 12 months ago and to the right would be right now, and it would automatically know what date it currently is.

And there would be no other function of this graph, it would simply show real time data for the last year up until now for the company and the logged in user.

The pie chart is good as it is

**Comment by invokelocal** [comment]
make the labels all capitol letters, like:

"COMPANY"
"YOU"

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
loking better, but where is the red line for the companies average rating per day?

**Comment by invokelocal** [comment]
looking*

**Comment by orientationsys** [comment]
Becase of the Data is same,so the lines are Overlapping

**Comment by invokelocal** [comment]
ohh ok, and does the chart now graph average rating data everyday?

**Comment by orientationsys** [comment]
Once you have enter new data in current Month,the graph average rating data will update,
