### ISSUE TITLE
"Local" plan

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#55]
In the new pricing structure the "Local" plan for $19 per month will only allow its users to enter in 20 customers per month (per billing cycle) so in the existing customers table, when they click on their customers name and the pop-up appears when they click the "DELETE" button a pop-up should appear that says:

"This function is not available in your plan, please upgrade to enable the Customer Delete feature" 

or if it is easier delete that button from the "Local" plan and keep the button and its functionality in the other plans.

Or option 3 if it is easier to keep a count of new customers in the database which counts the total entered within a billing cycle regardless of whether or not the client deletes the customers from their EXISTING CUSTOMERS table......

Which ever way you think is better.

**Comment by orientationsys** [comment]
Done ! Please check
