### ISSUE TITLE
EMAIL TEMPLATES

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#57]
EMAIL TEMPLATES - RATING REQUEST EMAIL - ADD THEME: 

The first form field says "NAME YOUR RATING REQUEST EMAIL:" change it to say "Email Title"

EMAIL TEMPLATES - RATING REQUEST EMAIL - Edit: 

After clicking edit the first form field says "NAME YOUR RATING REQUEST EMAIL:" change it to say "Email Title"

EMAIL TEMPLATES - REWARD EMAIL - ADD THEME: 

The first form field says "Ratereward Name" change it to say "Email Title"
The second form field says "User Name" change it to say "Who Is the Email From?"
The third form field says "Subject *" change it to say "What Is The Subject Line Of This Email? *"
The fourth form field says "Bodytext *" change it to say "What Do You Want The Body Of Your Email To Say? *"

EMAIL TEMPLATES - REWARD EMAIL - Edit: 

After clicking edit the first form field says "Ratereward Name" change it to say "Email Title"
The second form field now says "User Name" change it to say "Who Is the Email From?"
The third form field says "Subject *" change it to say "What Is The Subject Line Of This Email? *"
The fourth form field says "Bodytext *" change it to say "What Do You Want The Body Of Your Email To Say? *"

EMAIL TEMPLATES - LAST CHANCE EMAIL - ADD THEME: 

The first form field says "NAME YOUR RATING REQUEST EMAIL:" change it to say "Email Title"

EMAIL TEMPLATES - LAST CHANCE EMAIL - Edit: 

After clicking edit the first form field says "NAME YOUR RATING REQUEST EMAIL:" change it to say "Email Title"

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
That was quick!
