### ISSUE TITLE
Default Email Templates

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#58]
When a new account is set up I want the email template form fields to be the following by default:

RATING REQUEST EMAIL:

Email Title:
"Rate & Review"

Who Is the Email From?
"[user_fname  user_lname]"

What Is The Subject Line Of This Email? 
"Rate & Review Your Recent [company_name] Experience"

What Do You Want The Body Of Your Email To Say? *
"We value your opinion, please click on the link below to rate your experience."

-----------------------------------------------------------------------------------------------------------
REWARD EMAIL:

Email Title:
"Thank You"

Who Is the Email From?
"[user_fname  user_lname]"

What Is The Subject Line Of This Email? 
"Thank you for Rating [company_name]."

What Do You Want The Body Of Your Email To Say? *
"I just wanted to thank you for taking the time to rate your recent experience."

------------------------------------------------------------------------------------------------------------
LAST CHANCE EMAIL:

Email Title:
"Rate & Review Reminder"

Who Is the Email From?
"[user_fname  user_lname]"

What Is The Subject Line Of This Email? 
"Rate & Review reminder from [company_name] please take a minute to rate your experience with us."

What Do You Want The Body Of Your Email To Say? *
"We value your opinion, please click on the link below to rate your experience."

**Comment by orientationsys** [comment]
Done ! Please check
