### ISSUE TITLE
EMAIL TEMPLATE - Edit Headings

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#59]
in the EMAIL TEMPLATES - Edit on each email type, click the Edit link and change the headings of the Edit forms to the following:

RATING REQUEST EMAIL - Edit (link)
Change heading to: "EDIT RATING REQUEST EMAIL THEME"

REWARD EMAIL - Edit (link)
Change heading to: "EDIT REWARD EMAIL THEME"

LAST CHANCE EMAIL - Edit (link)
Change heading to: "EDIT LAST CHANCE EMAIL THEME"

**Comment by orientationsys** [comment]
Done ! Please check
