### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#60]
I want the following changes made to the homepage:

At the top where the two buttons say "Sign In" & "Register", make the sign in button red, and delete the register button.

The headline of the page should be near the top like in my picture and should say:
"LOCAL ONLINE MARKETING MADE SIMPLE"

Below the headline should be a centered / large video, make this video changeable from within revucue.com/admin.php so I can change the video and the picture.

Under the video is a simple form asking for the email address, and a button that says "GET STARTED"

Under the form field it says "*NO CREDIT CARD REQUIRED*"

Once the person clicks on get started they will get a welcome email from revucue, and will be directed to: http://revucue.com/user/create

their email address will pre-populate in the email address field.

![intropage](https://cloud.githubusercontent.com/assets/10223970/6408133/997543b4-be13-11e4-8a4f-050bb1ef43b4.png)

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
after I uploaded a video the form was not present, make less space between the menu bar and the heading and see is this fixes the problem.


![toobig](https://cloud.githubusercontent.com/assets/10223970/6416544/81a99b28-be6c-11e4-960a-0028d3f4c1b2.png)

**Comment by orientationsys** [comment]
Done! Please check
