### ISSUE TITLE
REGISTER PAGE

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#61]
the changes to the http://revucue.com/user/create page are as follows:

The background is the same picture used in other pages.

the RevuCue logo is at the top.

The button is red and says: "CREATE ACCOUNT"

![register](https://cloud.githubusercontent.com/assets/10223970/6408168/8e67d8aa-be14-11e4-99e5-df9ccbc1e171.png)

**Comment by orientationsys** [comment]
Done! Please check
