### ISSUE TITLE
After New User has created a new account

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#62]
First all users will start with a free account for 30 days or 20 new customers added, which ever comes first.

So after the new user clicks "CREATE ACCOUNT" they will be directed into the portal dashboard page, the logo by default will be the RevuCue logo and and since we have not gotten their name yet it will just say "Hello" in the upper left corner.

The new program intercom.io which we will set up next week will take care of guiding the user through the setup process.

While on the trial period directly below the vertical menu will be a "trial period countdown" so it will say: "17 DAYS LEFT IN TRIAL" indicating how many more days are left in the trial period.

Under the trial period counter will be a button that says "UPGRADE"

When a user clicks on upgrade is when they will be taken to the payment processing page, which should be the "BILLING" button within the portal, so from there they will choose which plan to go with.

Do not worry about the "http://revucue.com/user/information/id/33/message/email+send+success%21" page for now, we might not need this page now with the intercom.io functionality.

![upgrade](https://cloud.githubusercontent.com/assets/10223970/6408335/f062c9a4-be17-11e4-86cc-807477d61fd9.png)

**Comment by invokelocal** [comment]
Change the "17 DAYS LEFT IN TRIAL" to 

"17 DAYS / 19 NEW CUSTOMERS
      LEFT IN TRIAL PERIOD"

this will let the user know how many days are left and how many customers they can add before their trial period ends.

Center the text and below it would be the "UPGRADE" button as specified before.

**Comment by invokelocal** [comment]
Also in the "Local" plan only keep the customer count under the menu bar even after they have gone from free to paid, and have it say:

"14 OUT OF 20 CUSTOMERS
ADDED THIS MONTH" 

where 14 in the example is the amount of customers they have added so far this month.

Under the customer count still have the "UPGRADE" button show to allow the "Local" customers to easily upgrade their plan.

**Comment by invokelocal** [comment]
Instead of saying:

"17 DAYS / 19 NEW CUSTOMERS
LEFT IN TRIAL PERIOD"

Have it say:

"17 DAYS / 19 NEW CUSTOMERS
LEFT IN YOUR FREE TRIAL"

**Comment by orientationsys** [comment]
Done! Please check
