### ISSUE TITLE
30 day free trial page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#64]
for the web address: revucue.com/free30 the below picture represents how it should look. It will look almost exactly like the home page, at the top is the RevuCue logo, and if clicked it goes to the revucue home page. There is no menu bar on the "free30" page. The background is the same background as the home page, the video is the same video and also feeds from revucue.com/admin.php just like the video on the home page, the form below the video is the same as the home page, and this page does not scroll down because there is no more content just a background, logo, video, and simple form is all

![30free](https://cloud.githubusercontent.com/assets/10223970/6408438/db85271e-be19-11e4-8eca-04636621cb6a.png)

**Comment by orientationsys** [comment]
Done! Please check
