### ISSUE TITLE
The Next Step

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#65]
After the bugs are worked out and you have a minute take a look at this website: 

http://docs.intercom.io/Intercom-for-user-analysis/Tracking-User-Events-in-Intercom

it is the intercom.io page about captureing user behavior, it also has a link to thier API docs.
With this software I want you to code it (they say it is easy to code...) so that all of the logged in users behaviors & attributes can be seen within my intercom.io portal

This software will allow me to easily see who logs in the most, who spends the most, how many customers a client has entered and much more. I will be able to make pop-ups appear within the users portal automatically based on their actions and attributes. 

So when you get a minute take a look and familiarize yourself with this product.

And this will be the next step to get this enabled

Thanks!

**Comment by invokelocal** [comment]
For this intercom.io application I will creat all of the in-app (in revucue) messages that the clients will see, I just need you to code in all of the possible variables into the script like the clients customer count, subscription plan, code for actions of users using revucue's functionality, then I will be able to constantly update the users experience to enable them to get the most out of revucue, so program as many events and attributes into the intercom script as you can think of so I will have as many options to customize the users experience as possible

**Comment by orientationsys** [comment]
I am testing Intercom Api, But it needs the app_id and api_key. So can you send your Intercom Account to me and Let me test it.

**Comment by invokelocal** [comment]
Do not spend any time on intercom right now..... They are having issues with getting me started and say that everything will be working in a day or two, so until then on this issue............

**Comment by invokelocal** [comment]
APP NAME
RevuCue

APP ID
m3pysliz


API KEY		 
a76dae8f54c2a49b5d356daa7e87a84ddf479565

**Comment by invokelocal** [comment]
intercom should be fully functional!!
