### ISSUE TITLE
RevuCue has been Hacked

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#68]
Hello, 

There is a little emergency right now, RevuCue.com has been hacked, I called host gator and they say only the index file was changed. If you can as soon as possible can you delete the changed index file and upload the correct index file. I will forward you the email I got from host gator which has a new cpanel password

**Comment by orientationsys** [comment]
what is your cpanel the new password, Can you send it to my email (lz@orientationsys.com)

**Comment by invokelocal** [comment]
In 10 minutes I will be home and I can send

**Comment by invokelocal** [comment]
I forwarded the call from Hostgator yesterday to the email address that I
already had for you check email please

**Comment by orientationsys** [comment]
Done! Please check
