### ISSUE TITLE
Rating Averages

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#71]
In my friends new account, I just was looking around his portal and noticed that the "Rate %" in the user reports is 25% and on the dashboard the "Rate %" on the chart is 100%, these numbers should be the same at least at the beginning before additional users or locations are added.... also in his user report the "Average Star Rating " for the user / location & company is 14???????? it should be 5 at maximum, please check the mathematical formulas

**Comment by orientationsys** [comment]
what is your friends new account ?

**Comment by invokelocal** [comment]
username is: autocollectionofmurfreesboro@gmail.com
check the admin.php to get the password

also I missplled the email when I was setting it up so there are 3 accounts I think and only one is spelled correctly...... as above

**Comment by orientationsys** [comment]
I find that the autocollectionofmurfreesboro@gmail.com have 2 extra records about rating but there is just one customer records. So i think the error  mathematical formulas will Happen becase of the client delete the customer records , But in revucue.com , when the client delete the customer records , it do not delete the customer rate records.

**Comment by invokelocal** [comment]
I just deleted the records myself, they were test records

**Comment by orientationsys** [comment]
Now , I change the code. Once the customer have been deleted, the rate information about the delete customer will also be deleted! Done ! Please check

**Comment by invokelocal** [comment]
Nice, that looks good, but what about the Rate % on the User Report, it says 8%..... and on the dashboard the Rate % is accurate right now at 100%...

**Comment by orientationsys** [comment]
The Rate % in the Userreport Page is about  (Current Rate Counts/Have Sended Email Counts) Percentage,But the Rate % in the dashboard Page is about (Have Rated Customer Counts / All Customer Counts),So they are  Different calculation methods。。

**Comment by orientationsys** [comment]
And in the REVISED DASHBOARD DETAIL.Doc .Your say 	RATE % (what percentage of this users customers that have been emailed a RATING REQUEST email actually rated their experience, for example: User - Mike Hall sent 10 RATING REQUEST emails and 5 of those customers who received my email actually took the time to rate their experience so my RATE % would be 50% so maybe I could look back in my EXISTING CUSTOMER page and find out who didn’t rate their experience and send them a custom email or give those customers a call and try and encourage a review) In Userreport Page. And

**Comment by invokelocal** [comment]
ok I think I have confused myself on this one, I apologize for the changes but the rate% on the dashboard and on the user report I want it to calculate "Have Rated Customer Counts / All Customer Counts" so on the dashboard it will show the rate % for the entire company but in the user report it will show for the company, location, and user..... So keep the dashboard the same and just use that calculation for the user report.

I know I asked the report to be different before, but I think I made it too confusing so just have them both do the same calculations

**Comment by orientationsys** [comment]
Done! Please check
