### ISSUE TITLE
Auto Capitalization....

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#73]
Can you make the following form fields automatically be capitalized first letter, so if I enter my name like "mike hall" it will automatically be "Mike Hall", I noticed on the auto collection account that the customer entered her name in lower case letters, so any email she gets will look odd because they are lower case.:

First Name
Last Name
Company Name
Address Line 1
Address Line 2
City

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
sweeeet!
