### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#75]
on the home page, if I click on the RevuCue logo the browser will reload the page but it makes the video play automatically, but the image is still over the video so you hear the sound but do not see the movie. I want to keep the auto play functionality but only after you click on the image, somehow it now auto plays the video after clicking on the logo??

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
now the auto play does not work when I click on the "video image" I still want the video to play automatically, but not when you click on the revucue logo, only after you click on the video image

**Comment by orientationsys** [comment]
Done! Please check
