### ISSUE TITLE
Odd bug

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#76]
in the EXISTING CUSTOMERS table, if i click on a customers name to have the pop-up appear, and I click Delete, the pop-up goes away, and if I click on "2" (page two of the table), then click on "1" (page 1 of the table) the pop-up now appears again in front of page 1??? this is a odd bug but it happens evertime I try it

**Comment by invokelocal** [comment]
And if I click delete again (which the data has already been deleted) the pop-up will not go away, so my screen is blocked by the pop-up that will not close

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
sweet
