### ISSUE TITLE
New Accounts

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#79]
Once the user clicks "CREATE ACCOUNT" they should be taken directly into the portal dashboard.

The default "logo" should be RevuCue.

The default colors should be black background, red buttons, and grey fonts.

Once the user clicks upgrade, the plans that are at the top, the top 2 both say "Local+" the top one should just say "Local".

The label for the plans should be: "CHOOSE PLAN" and if possible I need to have a graphic to the right of the plan selector that will change when they click on a certain plan, that way I can describe the differences between the plans.

The button that says "DoDirectPay"" should be red, and say "Submit Payment"

I received 2 emails from revucue when I signed up a new test account, just send the first one the "Welcome to RevuCue" email and delete the "Verification Email".

Make the following changes to the "Welcome To RevuCUe" email and make it say the following:

Welcome to Revucue.com

If you need help during the set up process please call:
1-855-REV-UCUE

1-855-(738- 8283)

You can log into your portal by going to: revucue.com/site/login

Thank You,
1-855-REVU-CUE
If you wish to contact us, please do not reply directly to this email, please send emails to the email address in the signature above. Thank you.

**Comment by invokelocal** [comment]
black= #000000
button color= #e0111e
font color= #dcdde8

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
Awesome!!
