### ISSUE TITLE
RevuCue Main Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#8]
On the revucue.com main page there should be a button at the top that says "Portal" and if they are already signed in it takes the user to their pre-portal, if they are not signed in it takes them to the Log-in page

**Comment by orientationsys** [comment]
Down !Please check

**Comment by invokelocal** [comment]
On the "Home" button can you delete the drop down menu that is attached to "Home" button, this was a feature of the theme and not needed.

The "How it work" button change it to "How It Works" 

and can you move the "Portal" button to the right end of the list of buttons

**Comment by orientationsys** [comment]
Done!please check

**Comment by invokelocal** [comment]
AWESOME!
