### ISSUE TITLE
Daily Update Email

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#81]
the email subject would say:

"Daily Update: 3 New Reviews & 6 Customers Past Due" (were the numbers are the users current numbers) 

The body would have the RevuCue logo, and say:

"You have 3 New Customer Reviews! & 6 Customers Are 10 Days Past Due, click here to log into your account."

The "here" in the last sentence would be a link to revucue.com/site/login

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
Sweet
