### ISSUE TITLE
New User Defaults

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#82]
ADD LOCATION, right now in the new client default, in the ADD LOCATION page it says, "You must upgrade...." all accounts are allowed one location, so the message should only be there after the user adds their first location, and make the "UPGRADE" button red.

The FORM ELEMENTS, all buttons should be "OFF" by default except the required first name and email address ofcourse, it will be up to the user to turn on any other fields.

The INTERNAL REVIEW FORM TITLE by default should be "Thank You for rating us, please take a moment to write an honest review about your experience."

The default EMAIL TEMPLATES that we set up before should be active in the tables when a new user signs up

In the ADD / DELETE USERS page the warning should say: "To add additional users to your portal you must click “UPGRADE” the Local plan only allows for one user"

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
Nice!!
