### ISSUE TITLE
Billing Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#83]
Isn't there a simple billing table you can put here from PayPal?, nothing fancy just basic information

**Comment by invokelocal** [comment]
![billing](https://cloud.githubusercontent.com/assets/10223970/6478480/7cb7cf6e-c1f9-11e4-88bf-f02f722a2e3a.png)

**Comment by invokelocal** [comment]
The billing info is simple text, I would like it like this on the billing page, to describe the monthly charges, and a link to cancel the account, and if they click the link it be a pop-up and will tell the user to:

"Please call 1-855-REVU-CUE (1-855-738-8283) to cancel your account."

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
Sounds good, but on my "test accounts" I can't see anything, is there a way that I can see what each line says?

**Comment by orientationsys** [comment]
Because of your test accounts have not upgrade! SO there is no Billling with it. You can upgrade your test accounts.
