### ISSUE TITLE
RevuCue blog

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#84]
I want to add a blog to the site, but I want the url to be revucue.com/learn

I was thinking of using wordpress cms for the blog, are you familiar on how to integrate wordpress "blog" into an existing site?

This way I can use all of the seo tools wordpress has to offer while continuously creating content that hopefully will drive inbound traffic to revucue.com

Let me know what you think....

**Comment by orientationsys** [comment]
Done! Please check. The username is test, The password is 123456

**Comment by invokelocal** [comment]
Niice!
