### ISSUE TITLE
Dashboard Main Page

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#9]
At the top left of the main area of the dashboard above the "+ADD NEW CUSTOMER" button, delete the heading that says "[Company Name] welcome ! [User Name]" nothing should be here.

The "+ADD NEW CUSTOMER" button should be red.

Keep the chart from the theme that now says "Visitor Analytics", change that heading to say "CUSTOMER RATINGS" under that heading the text should say "Average customer rating for you and your company"

The Y-Axis should be the "Average Star Ratings" and represent the numbers between 1-5 stars

The X-Axis is the "Time Frame" and should represent a length of time

This chart will represent the average customer ratings over a length of time to let the client visually see if their ratings are improving or declining.

One line of the chart should be red and represent the companies' average star rating, and one line should be light grey and represent the signed in users' average rating

The time frame of the X-axis should be from when the client signed up until "now" by default

There should be some sort of selector to allow the user to choose what time frame the chart is representing

The Pie Chart to the right can be used, but I will provide detail in another issue

**Comment by invokelocal** [comment]
On the pie chart were it now says "1,225,729 visitors" change that to "[total number of new customers for the company] NEW CUSTOMERS"

were now the color is blue and says "56% return customers" I want that to be red and represent the percent of customers for the entire company that has rated, so that would be changed to
"[percentage that rated] RATED %"

and were it is now green and says "34% new visitors" change that to light grey and say "[percentage that did not rate] UNRATED %"

**Comment by invokelocal** [comment]
The map chart and the black large line that goes through the middle of the main area can be deleted, we will add more info-graphics to the dashboard in addition to the two charts above after you get back from vacation

**Comment by orientationsys** [comment]
Done! Please Check!

**Comment by invokelocal** [comment]
the http://revucue.com/admin/dashboard page is not loading at all on my browser at all right now, just a loading icon spinning but no error message and the page is not loading

**Comment by invokelocal** [comment]
this issue is only in chrome, in IE it is working

**Comment by orientationsys** [comment]
![qq 20150216173036](https://cloud.githubusercontent.com/assets/2968891/6209532/e5c9853c-b601-11e4-8fef-53b2b0fb9d2a.png)

**Comment by invokelocal** [comment]
this is how my Chrome is looking

![123456789](https://cloud.githubusercontent.com/assets/10223970/6209608/43efc6c8-b58d-11e4-88ea-377fe9756947.jpg)

**Comment by invokelocal** [comment]
After hours, my Chrome browser still looks the same! it is loading every other page before the portal, but the portal / dashboard is not loading still

**Comment by invokelocal** [comment]
Now it is working, and the favicon is there. I do not know what was different??
