### ISSUE TITLE
Dashboard Graph

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#90]
On the dashboard graph if February the average star rating is 4.63, the way you have it set up now in March at the beginning the average customer rating starts at 0, I do not want the average reset every month, I only want the months to track what the average rating were at that point in time, so if February was 4.64, then March should start at 4.63, and only go up or down as new ratings come in, and so that means February 1rst = 4.63, and other ratings came in and on March 1rst = 4.14, and so on, but the rating average is the total over all time they have been with revucue, the graph just charts those numbers on a certain day per month.....

**Comment by orientationsys** [comment]
Done! Please check

**Comment by invokelocal** [comment]
Nice, I just noticed somethin though, the graph key that says "Company & You" is on the right of the graph and this would block the view of the line, can you move the graph key to the left side of the graph

**Comment by orientationsys** [comment]
Done ! Please check.
