### ISSUE TITLE
Type Of Business

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#92]
Now that a new user goes from "Create Account" directly to the dashboard, the user never enters their 'TYPE OF BUSINESS" so add a drop down form field labeled "TYPE OF BUSINESS" to the company profile page

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
The "TYPE OF BUSINESS" should be in the COMPANY PROFILE, but it should not have an affect on the PREVIEW

**Comment by invokelocal** [comment]
This way all USER level users will automatically be in the category that the company selected

**Comment by invokelocal** [comment]
the label for the form field should be "TYPE OF BUSINESS" right now it is "Typeofbusiness"

**Comment by orientationsys** [comment]
Done ! please check

**Comment by invokelocal** [comment]
perfect
