### ISSUE TITLE
intercom Events & Attributes

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#93]
EVENTS:
Clicked on ADD NEW CUSTOMER
Went to EXISTING CUSTOMERS page
Clicked on import customers
Clicked on export customers
Clicked on “EDIT PROFILE” in edit profile page
Changed Password
Clicked on “VIDEO FAQ’s”
Clicked on contact support
Clicked company profile
Clicked UPDATE COMPANY PROFILE
Went to ADD LOCATION page
Clicked ADD LOCATION button
Deleted Location
Clicked Edit Location
Went to Billing page
Updated Form Elements
Went to FORM ELEMENTS page
Went to RATE WEBPAGE page
Went to REVIEW LINKS page
Clicked ADD LINK
Went to EMAIL TEMPLATES
Clicked on ADD THEME in Rating Request Email
Clicked on ADD THEME in Reward Email
Clicked on ADD THEME in Last Chance Email
Went to USER REPORTS
Clicked on EXPORT CSV file in user reports
Went to ADD / DELETE USER
Clicked Add User in ADD / DELETE USER page
Deleted User
Clicked On cancel subscription
Clicked on Customers name to make pop-up appear
Within customer pop-up clicked on SAVE AS PDF
Within customer pop-up clicked on EDIT
Within customer pop-up clicked on DELETE
Clicked on customers email address in pop-up or EXISTING CUSTOMERS table
Sent customer a Email from pop-up
Sent customer a RATING REQUEST email from pop-up
Clicked on customer review inside of the EXISTING CUSTOMERS table

ATTRIBUTES:
Total import customer count
Export customer count
Average Star rating for User, Company and Location
Date Selector ON
Date Selector OFF
Number of locations
Type of Business (from company profile)
Number of review links
On Local plan
On Local+ Plan
On Empire Plan
Used Coupon code GetReviewsNow
Used Coupon code GoldenTesterPro
Used Coupon code 5StarsAllDay
Number of customers entered
% of customers that rated for the user, location, company
Number of users
State that the company is located in

**Comment by invokelocal** [comment]
Attribute:

Monthly bill $ amount

**Comment by invokelocal** [comment]
Atrribute:

ADMIN USER level or
USER level

**Comment by invokelocal** [comment]
Attribute:

Last time a user added a customer

**Comment by orientationsys** [comment]
I Add the intercom Event with Click Add New Customer, But i do not know Whether it is Success to Add the intercom. So Please log your account to Confirm whether is it Success?

**Comment by invokelocal** [comment]
Yes! 

"CLICKED ON ADD NEW CUSTOMER"

is in the portal

**Comment by invokelocal** [comment]
I think you can add all of the page URL's in the echo's as well.... idk

**Comment by orientationsys** [comment]
I am testing the Intercom Event about the metadata like the blew image

**Comment by orientationsys** [comment]
![qq 20150306125500](https://cloud.githubusercontent.com/assets/2968891/6521026/852c3dce-c40b-11e4-910d-43f56af6b5ae.png)

**Comment by orientationsys** [comment]
![qq 20150306141414](https://cloud.githubusercontent.com/assets/2968891/6521029/955b6b66-c40b-11e4-8096-5800d5f119ef.png)

**Comment by orientationsys** [comment]
so are you get the metadata information in your intercom account ??

**Comment by invokelocal** [comment]
I am not sure on were to find this information within the intercom portal, One minute

**Comment by invokelocal** [comment]
I do not see that one yet but maybe an import action has to take place before intercom recognizes it idk ......

**Comment by orientationsys** [comment]
can you find the event name in your intercom account. like 'Clicked on ADD NEW CUSTOMER','Went to Billing page' and so on .  if you can , Please screenshot a image to me

**Comment by invokelocal** [comment]
![clickedon](https://cloud.githubusercontent.com/assets/10223970/6521200/e21e2ee2-c399-11e4-821c-a9e62bb3d129.png)

**Comment by orientationsys** [comment]
I want to know Whether the metadata information insert into the intercom . So May be could you give me your intercom account information . let me log in then test it.

**Comment by invokelocal** [comment]
![password](https://cloud.githubusercontent.com/assets/10223970/6521380/bf66aff2-c39c-11e4-8959-03261f4bcb05.png)

**Comment by invokelocal** [comment]
I will change this information tomorrow for security

**Comment by orientationsys** [comment]
Thank you

**Comment by orientationsys** [comment]
I think i find the metadata information . you can look these in below image

**Comment by orientationsys** [comment]
![qq 20150306153906](https://cloud.githubusercontent.com/assets/2968891/6521828/65c7b98e-c417-11e4-9c88-6d6052ec56ec.png)

**Comment by invokelocal** [comment]
ok, i will have to ask intercom on how I can get the "attributes" to show up on the main table of the portal..... so I could list the users by how many customers they have, rating average and so on

**Comment by invokelocal** [comment]
is there a way to put these attributes in the "DISPLAYED USER ATTRIBUTES" drop down menu in the portal, so the data will show on the main table?

**Comment by invokelocal** [comment]
in the intercom video at: 

http://docs.intercom.io/configuring-Intercom/Send-custom-user-attributes-to-Intercom

it says these attributes will show up on the table?......

**Comment by invokelocal** [comment]
Company Name should be an attribute as well

**Comment by orientationsys** [comment]
Frist Step: Click the username in the table . you will see the information about the clicked user. So the attribute you will see in that page

**Comment by invokelocal** [comment]
I understand that it is there, but I cannot use that data, I need it to somehow be in the DISPLAYED USER ATTRIBUTES so for example I want to send a message to all users that have a rating of 4.0 or higher and add 100 customers or more a month, maybe some of the attributes have to be added to the events?? idk

**Comment by orientationsys** [comment]
oh , I test it . It will success in the intercom

**Comment by orientationsys** [comment]
![qq 20150306163212](https://cloud.githubusercontent.com/assets/2968891/6522337/cddd7ebc-c41e-11e4-9a46-28eda2ecf1b0.png)

**Comment by orientationsys** [comment]
So which attribute do you want .

**Comment by orientationsys** [comment]
i think the attribute 'Export customer count' is hard to Statistics. So it is best to delete this attribute.

**Comment by invokelocal** [comment]
OK, that is fine to delete, I want to use the attributes that have number values like how many new customers, monthly spend, average ratings, and any other data that can be quantified...

**Comment by invokelocal** [comment]
I see the TOTAL IMPORT CUSTOMERS in there but it does not recognize the data as a number I do not think, so for instance I can not set a numerical value to the data to say for example send a message to all users who have imported over 100 rows of customer data

**Comment by orientationsys** [comment]
I think you can setting them in the intercom

**Comment by orientationsys** [comment]
![qq 20150306170420](https://cloud.githubusercontent.com/assets/2968891/6522740/4bd7a91a-c423-11e4-856d-f2b49764a3e5.png)

**Comment by orientationsys** [comment]
Done ! Please check
