### ISSUE TITLE
End Of The Trial 

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#94]
At the end of the trial period whether it is past the 30 days or the 20 new customers added, what happens now?

I think it would be best to allow that user to still log in, but any button they click would trigger a pop-up that says:

"Your free trial has ended, please click on UPGRADE below to continue to use RevuCue for as little as $19 per month!"

and there would be a button on the pop-up that would say "UPGRADE" and once clicked the user would be directed to the page where they could upgrade their plan.

Even after the users trial has ended they should continue to recieve the DAILY UPDATE emails every day.......

**Comment by orientationsys** [comment]
Done ! Please check
