### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#95]
The DAILY UPDATE email should have a "Unsubscribe" functionality in case someone does not want to receive it everyday, and hopefully they can click on Unsubscribe instead of putting it into spam folder

**Comment by orientationsys** [comment]
Done ! Please check. The functionality is in blew Picture which Ring out Section.

**Comment by orientationsys** [comment]
![qq 20150305170838](https://cloud.githubusercontent.com/assets/2968891/6502053/b42041ea-c35a-11e4-8c47-e10a2f0c75ad.png)

**Comment by invokelocal** [comment]
Looks Good, but format it like this: "Unsubscribe: Daily Emails"  with the ":"

**Comment by orientationsys** [comment]
Done ! Please check
