### ISSUE TITLE
Last Chance Emails

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#96]
as a "test customer" I have not been recieving Last Chance Emails 7 days after I received the Rating Request Email.

The Last Chance Email should be sent automatically from the user to the customer 7 days after the Rating Request Email if the customer has not yet rated there experience....

I just wanted to bring up this issue to see if you had those emails doing something else, or if they are not working properly....

**Comment by orientationsys** [comment]
what method you send the rating request Email? Is it by Corn job or In the exstingcustomer Page you send the rating request Email??

**Comment by orientationsys** [comment]
If you send the rating request Email in the exsting customer . The customer will not recieving Last Change Email

**Comment by orientationsys** [comment]
IN the REVISED DASHBOARD DETAIL .Doc , you say that

**Comment by orientationsys** [comment]
![qq 20150305163756](https://cloud.githubusercontent.com/assets/2968891/6501682/70f79d7c-c356-11e4-8193-e1c6baba3920.png)

**Comment by invokelocal** [comment]
These are customers I entered into the ADD NEW CUSTOMER form, and if the test customer did not rate, the customers are not receiving the LAST CHANCE email from the user / RevuCue

**Comment by orientationsys** [comment]
Done ! Please check.

**Comment by invokelocal** [comment]
I just got a last chance email, so I guess it is working, so problem solved

**Comment by orientationsys** [comment]
Becase of there is a error in the last chance email template! So I found it and solved it
