### ISSUE TITLE
Dashboard Graph Issues!

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#97]
On the average customer rating graph in my test account (invokelocal@gmail.com) the star rating went from 3.63 I think yesterday to 2.24 now and no new ratings were inputted, and also the pie chart went from 65% rated yesterday to now it shows 95% rated.

Some coding must have altered the calculations of these charts......

The rating percent is incorrect at 95% and it was correct at 65%

**Comment by invokelocal** [comment]
![myscreen](https://cloud.githubusercontent.com/assets/10223970/6520377/64005832-c38a-11e4-8f57-cc334946af96.png)

**Comment by orientationsys** [comment]
In the database , I found that ,there is 43 customers in the invokelocal@gmail.com. And 42 customers have been rated!

**Comment by orientationsys** [comment]
41 customers have been rated

**Comment by orientationsys** [comment]
![qq 20150306125500](https://cloud.githubusercontent.com/assets/2968891/6520426/76522576-c400-11e4-97a3-fe59675403a8.png)

**Comment by invokelocal** [comment]
go into my portal, there are many test customers who did not rate?????

![bug](https://cloud.githubusercontent.com/assets/10223970/6520447/4be55ef4-c38b-11e4-8382-c0512e7d9d1f.png)

**Comment by invokelocal** [comment]
I just counted manually and there are 24 customers who have rated

**Comment by invokelocal** [comment]
there are 43 customers, but only 24 ratings.....

**Comment by orientationsys** [comment]
I know the reason why it will happen now!

**Comment by invokelocal** [comment]
that's good you identified the problem, is it with the code or with user interaction, and can it be fixed?

**Comment by orientationsys** [comment]
Done! Please check

**Comment by orientationsys** [comment]
I think also have a error about it !

**Comment by orientationsys** [comment]
Done ! plase check

**Comment by invokelocal** [comment]
Nice
