### ISSUE TITLE
intercom

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#98]
I took a quick look at auto collection of murfreesboro a minute ago and the intercom icon was not at the bottom right of the screen, any reason for this?

**Comment by orientationsys** [comment]
![qq 20150306124617](https://cloud.githubusercontent.com/assets/2968891/6520352/3b0477c2-c3ff-11e4-8316-fca19b2a9825.png)

**Comment by invokelocal** [comment]
![myscreen](https://cloud.githubusercontent.com/assets/10223970/6520362/2cb1f0d4-c38a-11e4-8d48-de9f8c302fcb.png)

**Comment by invokelocal** [comment]
use this pic for the other issue....

**Comment by invokelocal** [comment]
In my browser it shows auto sollection with 2 customers and no icon at the bottom?????

**Comment by invokelocal** [comment]
![hans](https://cloud.githubusercontent.com/assets/10223970/6520416/09b10e0c-c38b-11e4-8e93-456abd17cb1f.png)

**Comment by invokelocal** [comment]
Intercom works in my test accounts, and it is showing info in my portal about auto collection of murfreesboro but it doesn't show the icon in the auto collection portal, it did when I first set them up

**Comment by orientationsys** [comment]
Is it works well now??

**Comment by invokelocal** [comment]
Yes, I will talk to intercom but it is working yes
