### ISSUE TITLE
Upgrade Pop-Up

### ISSUE THREAD

**Issue by invokelocal** [orientationsys/revucue#99]
The Upgrade Pop-Up currently says:

"UPGRADE
Your free trial has ended, please click on UPGRADE below to continue to use RevuCue for as little as $19 per month!"

Change it to say:

"UPGRADE
Your free trial has ended, please click on UPGRADE to continue to use RevuCue for as little as $19 per month!"

(with "UPGRADE" still being a clickable link)

**Comment by orientationsys** [comment]
Done ! Please check

**Comment by invokelocal** [comment]
sweet
